import { MigrationInterface, QueryRunner } from 'typeorm';

export class FillCarBrands1741809260107 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Добавляем бренды автомобилей с полями title и slug
    await queryRunner.query(`
      INSERT INTO "brand" ("title", "slug")
      VALUES
        ('Audi', 'audi'),
        ('BMW', 'bmw'),
        ('Mercedes-Benz', 'mercedes-benz'),
        ('Toyota', 'toyota'),
        ('Ford', 'ford'),
        ('Honda', 'honda'),
        ('Volkswagen', 'volkswagen'),
        ('Tesla', 'tesla'),
        ('Nissan', 'nissan'),
        ('Hyundai', 'hyundai'),
        ('Chevrolet', 'chevrolet'),
        ('Kia', 'kia'),
        ('Volvo', 'volvo'),
        ('Porsche', 'porsche'),
        ('Lexus', 'lexus'),
        ('Subaru', 'subaru'),
        ('Mazda', 'mazda'),
        ('Jeep', 'jeep'),
        ('Land Rover', 'land-rover'),
        ('Ferrari', 'ferrari'),
        ('Lamborghini', 'lamborghini'),
        ('Aston Martin', 'aston-martin'),
        ('Bentley', 'bentley'),
        ('Rolls-Royce', 'rolls-royce'),
        ('Maserati', 'maserati'),
        ('Alfa Romeo', 'alfa-romeo'),
        ('Fiat', 'fiat'),
        ('Peugeot', 'peugeot'),
        ('Renault', 'renault'),
        ('Citroën', 'citroen'),
        ('Skoda', 'skoda'),
        ('Seat', 'seat'),
        ('Opel', 'opel'),
        ('Mini', 'mini'),
        ('Jaguar', 'jaguar'),
        ('Mitsubishi', 'mitsubishi'),
        ('Suzuki', 'suzuki'),
        ('Dodge', 'dodge'),
        ('Chrysler', 'chrysler'),
        ('Buick', 'buick'),
        ('Cadillac', 'cadillac'),
        ('GMC', 'gmc'),
        ('Infiniti', 'infiniti'),
        ('Acura', 'acura'),
        ('Genesis', 'genesis'),
        ('DS Automobiles', 'ds-automobiles'),
        ('Lada', 'lada'),
        ('Tata', 'tata'),
        ('Mahindra', 'mahindra'),
        ('Geely', 'geely'),
        ('BYD', 'byd'),
        ('Great Wall', 'great-wall'),
        ('Chery', 'chery'),
        ('Haval', 'haval'),
        ('SsangYong', 'ssangyong'),
        ('Isuzu', 'isuzu'),
        ('Daihatsu', 'daihatsu'),
        ('Smart', 'smart'),
        ('McLaren', 'mclaren'),
        ('Bugatti', 'bugatti'),
        ('Pagani', 'pagani'),
        ('Koenigsegg', 'koenigsegg'),
        ('Rimac', 'rimac'),
        ('Rivian', 'rivian'),
        ('Lucid Motors', 'lucid-motors'),
        ('Polestar', 'polestar'),
        ('NIO', 'nio'),
        ('XPeng', 'xpeng'),
        ('Li Auto', 'li-auto'),
        ('Faraday Future', 'faraday-future'),
        ('Lordstown Motors', 'lordstown-motors'),
        ('Nikola', 'nikola'),
        ('Canoo', 'canoo'),
        ('Fisker', 'fisker'),
        ('Arrival', 'arrival'),
        ('Bollinger', 'bollinger'),
        ('BYTON', 'byton'),
        ('Karma', 'karma'),
        ('Zotye', 'zotye'),
        ('Borgward', 'borgward'),
        ('SAIC Motor', 'saic-motor'),
        ('Dongfeng', 'dongfeng'),
        ('Changan', 'changan'),
        ('FAW', 'faw'),
        ('BAIC', 'baic'),
        ('JAC Motors', 'jac-motors'),
        ('Wuling', 'wuling'),
        ('Haima', 'haima'),
        ('ZX Auto', 'zx-auto'),
        ('JMC', 'jmc'),
        ('Lifan', 'lifan'),
        ('Hawtai', 'hawtai'),
        ('Brilliance', 'brilliance'),
        ('Changfeng', 'changfeng'),
        ('Gonow', 'gonow'),
        ('Hafei', 'hafei'),
        ('Jonway', 'jonway'),
        ('Landwind', 'landwind'),
        ('Luxgen', 'luxgen'),
        ('Qoros', 'qoros'),
        ('Roewe', 'roewe'),
        ('Soueast', 'soueast'),
        ('Yema', 'yema'),
        ('Zinoro', 'zinoro');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Удаляем добавленные данные при откате миграции
    await queryRunner.query(`
      DELETE FROM "brand"
      WHERE "slug" IN (
        'audi', 'bmw', 'mercedes-benz', 'toyota', 'ford',
        'honda', 'volkswagen', 'tesla', 'nissan', 'hyundai',
        'chevrolet', 'kia', 'volvo', 'porsche', 'lexus',
        'subaru', 'mazda', 'jeep', 'land-rover', 'ferrari',
        'lamborghini', 'aston-martin', 'bentley', 'rolls-royce',
        'maserati', 'alfa-romeo', 'fiat', 'peugeot', 'renault',
        'citroen', 'skoda', 'seat', 'opel', 'mini', 'jaguar',
        'mitsubishi', 'suzuki', 'dodge', 'chrysler', 'buick',
        'cadillac', 'gmc', 'infiniti', 'acura', 'genesis',
        'ds-automobiles', 'lada', 'tata', 'mahindra', 'geely',
        'byd', 'great-wall', 'chery', 'haval', 'ssangyong',
        'isuzu', 'daihatsu', 'smart', 'mclaren', 'bugatti',
        'pagani', 'koenigsegg', 'rimac', 'rivian', 'lucid-motors',
        'polestar', 'nio', 'xpeng', 'li-auto', 'faraday-future',
        'lordstown-motors', 'nikola', 'canoo', 'fisker', 'arrival',
        'bollinger', 'byton', 'karma', 'zotye', 'borgward',
        'saic-motor', 'dongfeng', 'changan', 'faw', 'baic',
        'jac-motors', 'wuling', 'haima', 'zx-auto', 'jmc',
        'lifan', 'hawtai', 'brilliance', 'changfeng', 'gonow',
        'hafei', 'jonway', 'landwind', 'luxgen', 'qoros',
        'roewe', 'soueast', 'yema', 'zinoro'
      );
    `);
  }
}
