name: Dev CI

on:
  push:
    branches:
      - master

# Добавляем конфигурацию concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - name: Build backend Docker image
        run: |
          echo "Building backend Docker image..."
          docker build --target backend --rm -t beznomera:backend https://github.com/paulislava/beznomera.git
          docker stop beznomera_backend || true
          docker rm -f beznomera_backend || true

          docker run --name beznomera_backend -d -it --network host --env-file /home/user/web/beznomera.net/web.env -v /home/user/web/beznomera.net/config-backend.yaml:/config.yaml -v /home/user/web/beznomera.net/ip-location-data:/app/node_modules/ip-location-api/data beznomera:backend
          docker rmi $(docker images --filter "dangling=true" -q --no-trunc beznomera_backend) || true

  # build-frontend:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Build frontend Docker image
  #       run: |
  #         echo "Building frontend Docker image..."

  #         # Собираем образ с переменными окружения
  #         docker build --rm -f frontend.Dockerfile -t beznomera:frontend https://github.com/paulislava/beznomera.git
          
  #         docker stop beznomera_frontend || true
  #         docker rm -f beznomera_frontend || true

  #         docker run --name beznomera_frontend -it -d -p 3001:80 -v /home/user/web/beznomera.net/frontend.env:/.env beznomera:frontend
  #         docker rmi $(docker images --filter "dangling=true" -q --no-trunc beznomera_frontend) || true

  build-web:
    runs-on: self-hosted
    needs:
      - build-backend
    steps:
      - name: Build web Docker image
        run: |
          echo "Building web Docker image..."
          docker build --target web --rm -f web.Dockerfile -t beznomera:web https://github.com/paulislava/beznomera.git
          docker stop beznomera_web || true
          docker rm -f beznomera_web || true

          docker run --name beznomera_web -d -it -p 4000:3000 --env-file /home/user/web/beznomera.net/web.env beznomera:web
          docker rmi $(docker images --filter "dangling=true" -q --no-trunc beznomera_web) || true

  # clean:
  #   runs-on: self-hosted
  #   needs:
  #     # - build-frontend
  #     - build-backend
  #     - build-web
  #   if: always()
  #   steps:
  #     - name: Clean unused containers and volumes
  #       run: |
  #         echo "Deleting unused containers, volumes..."
  #         docker system prune -a -f

