name: Dev CI

on:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - name: Build backend Docker image
        run: |
          echo "Building backend Docker image..."
          docker build --target backend --rm -t beznomera:backend .
          docker run -d -it --network host -v /home/admin/web/beznomera.paulislava.space/config-backend.yaml:/config.yaml -e ROUTE_PREFIX=/api beznomera:backend

  build-frontend:
    runs-on: self-hosted
    steps:
      - name: Build frontend Docker image
        run: |
          echo "Building frontend Docker image..."
          frontend_backend_url=/api telegram_bot_name=beznomera_bot docker build --rm -f frontend.Dockerfile -t beznomera:frontend .
          docker run -it -d -p 4000:80 beznomera:frontend

  clean:
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Clean unused containers and volumes
        run: |
          echo "Deleting unused containers, volumes..."
          docker container prune -f
          docker volume prune -f
