name: Dev CI

on:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Build backend Docker image
        if: ${{ !contains(steps.changed-files.outputs.all_changed_files, 'packages/') || contains(steps.changed-files.outputs.all_changed_files, 'packages/backend/') || contains(steps.changed-files.outputs.all_changed_files, 'packages/shared/') }}
        run: |
          echo "Building backend Docker image..."
          docker build --target backend --rm -t beznomera:backend https://github.com/paulislava/beznomera.git
          docker stop beznomera_backend || true
          docker rm -f beznomera_backend || true

          docker run --name beznomera_backend -d -it --network host -v /home/admin/web/beznomera.paulislava.space/config-backend.yaml:/config.yaml -v /home/admin/web/beznomera.paulislava.space/ip-location-data:/app/node_modules/ip-location-api/data  -e ROUTE_PREFIX=/api beznomera:backend
          docker rmi $(docker images --filter "dangling=true" -q --no-trunc beznomera_backend) || true

  build-frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Build frontend Docker image
        if: ${{ !contains(steps.changed-files.outputs.all_changed_files, 'packages/') || contains(steps.changed-files.outputs.all_changed_files, 'packages/frontend/') || contains(steps.changed-files.outputs.all_changed_files, 'packages/shared/') }}
        run: |
          echo "Building frontend Docker image..."
          frontend_backend_url=/api telegram_bot_name=beznomera_bot docker build --rm -f frontend.Dockerfile -t beznomera:frontend https://github.com/paulislava/beznomera.git
          docker stop beznomera_frontend || true
          docker rm -f beznomera_frontend || true

          docker run --name beznomera_frontend -it -d -p 4000:80 beznomera:frontend
          docker rmi $(docker images --filter "dangling=true" -q --no-trunc beznomera_frontend) || true

  clean:
    runs-on: self-hosted
    needs:
      - build-frontend
      - build-backend
    steps:
      - name: Clean unused containers and volumes
        run: |
          echo "Deleting unused containers, volumes..."
          docker container prune -f
          docker image prune -f
          docker volume prune -f
